### ISSUE TITLE
Include engine declaration in package.json file

### ISSUE THREAD

**Issue by kali-chip** [alaingalvan/webgl-seed#2]
Please consider including the minimum required version for NodeJS on the `package.json` file.

```javascript
{ "engines" : { "node" : ">=12.0" } }
```

I don't know what the exact version is, but I do know that the current webpack version needs at least a `10.13.0` version and trying to run this with an older version fails rather unhelpfully.

**Comment by alaingalvan** [comment]
Thanks! I went ahead engines to the `package.json` file here at b9f99bc4da9144b312f615aff41e176a243ca744.

I'll go ahead and test it out on my end before closing this issue. 👍

EDIT: So looking at Webpack's `package.json` file for `4.41.5` it seems they support any version greater than or equal to `6.11.5` (though maybe some other dependency required a higher something closer to `10.13.0`):

```json
"engines": { "node": ">=6.11.5" }`
```

Tested this project on an older computer with Node `9.7.1`  and it seemed to work fine. In any case, I'll leave this project with the requirement of Node `12.x` anyways, thanks!
